---
title: "GLMM"
format: pdf
editor: visual
---

removido do yaml: jupyter: python3

Executa por defeito no directorio do documento

## Python Setup:

```{python}
import matplotlib.pyplot as plt
```

You can add options to executable code like this

```{python}
#| echo: false


plt.plot([1, 2, 3, 4])
plt.ylabel('some numbers')
plt.show()
```

## R Setup

```{r}
#| eval: false
install.packages(c("lme4", "MASS", "vcdExtra", "bbmle", "MuMIn",
    "ggplot2", "DescTools", "remotes", "gridExtra", "lattice"),
    repos = "http://cran.us.r-project.org", quiet = TRUE)
```

The `echo: false` option disables the printing of code (only output is displayed).

```{r}
#| include: false
library(tidyverse)
library(lme4)
library(MASS)
library(vcdExtra)
library(bbmle)
library(MuMIn)
library(ggplot2)
library(DescTools)
library(remotes)
library(gridExtra)
library(lattice)

source('chapters/auxil/glmm_funs.R')
```

```{r}
#| include: true
data(iris)
ggplot(iris) + 
  geom_point(aes(x = Sepal.Length,
                 y = Sepal.Width))
```

## GLM Workshop

Exercicio 4.1 3 species, 6 sites to be compared. Is trophic position influenced by fish size?

```{r}
#| eval: true

fish.data = read.csv("chapters/data/qcbs_w7_data.csv",
                     stringsAsFactors = TRUE)

fig = theme_bw() + theme(panel.grid.minor = element_blank(),
    panel.grid.major = element_blank(), panel.background = element_blank(),
    strip.background = element_blank(), strip.text.y = element_text(),
    legend.background = element_blank(), legend.key = element_blank(),
    panel.border = element_rect(colour = "black", fill = NA))

plot = ggplot(aes(Fish_Length, Trophic_Pos), data = fish.data)
```

```{r}
#| eval: true
# Plot 1 - All data
plot + geom_point(aes(color = Lake)) + labs(x = "Length (mm)", y = "Trophic position",
    title = "All data") + fig

# Plot 2 - By species
plot + geom_point() + facet_wrap(~Fish_Species) + labs(x = "Length (mm)",
    y = "Trophic position", title = "By species") + fig

# Plot 3 – By lake
plot + geom_point() + facet_wrap(~Lake) + labs(x = "Length (mm)",
    y = "Trophic position", title = "By lake") + fig
```
